### ISSUE TITLE
Help with an advice - stuck in a browser window after pressing the button "Allow"

### ISSUE THREAD

**Issue by golovko** [CORDEA/evre#1]
Hi, Yoshihiro. Thank you very much for the article on Medium!
May I ask you for some advice?
I've downloaded the example you provided (from GitHub) and tried to run it but when I try to authorise with my Google account I get stuck in a browser window on a page google.com after I press the button "Allow". It seems that the redirect doesn't work correctly or I did something wrong.
Thank you.
---
I added a credential in https://console.cloud.google.com/ for the OAuth Android app type.
In the project I put secret.txt file with ClientId

**Comment by CORDEA** [comment]
I guess there's a problem with your deep linking configuration if the app doesn't open after the approval process. I recommend checking the deep link documentation and OAuth client configuration for Google Cloud. Unfortunately, there is not much I can comment on.

**Comment by golovko** [comment]
Thanks for your response! will try to figure it out.
